[package]
name = "libnss-webnis"
version = "0.1.0"
authors = ["mikevs <mikevs@xs4all.net>"]

[dependencies]
libc = "0.2"
log = { version = "0.4.3", features = ["release_max_level_info"] }
env_logger = "0.5.11"

[lib]
name = "nss_webnis"
crate-type = [ "cdylib", "rlib" ]

