[package]
name = "webnis-pam"
version = "0.1.0"
authors = ["mikevs <mikevs@xs4all.net>"]

[dependencies]
percent-encoding = "1.0.1"
pamsm = "0.2.0"

[lib]
name = "pam_webnis"
crate-type = [ "cdylib" ]

