[server]
  listen = [ "0.0.0.0:3245", "[::]:3246" ]
  tls = true
  cert_file = "/etc/ssl/private/wildcard.xs4all.nl.pfx"
  cert_password = ""

[[domain]]
  name = "xs4all.nl"
  db_dir = "/var/yp/xs4all.nl"
  maps = [ "passwd", "group", "gidlist" ]
  default = true
  auth = "adjunct"

[[domain]]
  name = "shell.xs4all.nl"
  db_dir = "/var/yp/shell.xs4all.nl"
  maps = [ "passwd", "group" ]

[auth.adjunct]
  map = "adjunct"
  key = "name"
  shells = "normal"

[shells.normal]
  allow = [ "bash", "csh", "ksh", "sh", "tcsh", "zsh" ]

[map.passwd.byname]
  key = "name"
  key_alias = { user = "name" }
  map_format = "passwd"
  map_type   = "gdbm"
  map_file   = "passwd.byname"

[map.passwd.byuid]
  key = "uid"
  map_format = "passwd"
  map_type   = "gdbm"
  map_file = "passwd.byuid"

[map.adjunct]
  key = "name"
  map_format = "adjunct"
  map_type   = "gdbm"
  map_file = "passwd.adjunct.byname"

[map.group]
  keys = [ "name", "gid" ]
  map_type = "json"
  map_file = "group"

[map.gidlist]
  [map.gidlist.json]
  key = "name"
  map_type = "json"
  map_file = "gidlist"

