[server]
  listen = [ "0.0.0.0:3245", "[::]:3245" ]
  #tls = true
  key_file = "/etc/ssl/private/wildcard.xs4all.net.key"
  crt_file = "/etc/ssl/certs/wildcard.xs4all.net.crt"
  cert_password = ""

[lua]
  script = "hello.lua"

[[domain]]
  name = "xs4all.nl"
  #password = "donkey jaw"
  db_dir = "/var/yp/xs4all.nl"
  maps = [ "passwd", "group", "gidlist", "wdsl", "seven" ]
  default = true
  auth = "adjunct"

[[domain]]
  name = "shell.xs4all.nl"
  db_dir = "/var/yp/shell.xs4all.nl"
  maps = [ "passwd", "group" ]

[auth.adjunct]
  map = "adjunct"
  key = "name"
  shells = "normal"

[shells.normal]
  allow = [ "bash", "csh", "ksh", "sh", "tcsh", "zsh" ]

[map.passwd.byname]
  key = "name"
  key_alias = { user = "name" }
  map_format = "passwd"
  map_type   = "gdbm"
  map_file   = "passwd.byname"

[map.passwd.byuid]
  key = "uid"
  map_format = "passwd"
  map_type   = "gdbm"
  map_file = "passwd.byuid"

[map.adjunct]
  key = "name"
  map_format = "adjunct"
  map_type   = "gdbm"
  map_file = "passwd.adjunct.byname"

[map.group]
  keys = [ "name", "gid" ]
  map_type = "json"
  map_file = "group"

[map.gidlist]
  [map.gidlist.json]
  key = "name"
  map_type = "json"
  map_file = "gidlist"

[map.seven]
  # key is just your regular key
  key = "user"
  # type is lua, means it's a function we call
  map_type   = "lua"
  # and this is the name of the function
  map_file = "map_seven"

[map.wdsl.byname]
  key = "user"
  map_format = "kv"
  map_type   = "gdbm"
  map_file   = "ip.wdsl.byname"

